name: project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  gap: ^3.0.1
  logger: ^2.5.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  timeago: ^3.3.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  fl_chart: ^1.0.0
  flutter_screenutil: ^5.9.3
  toastification: ^3.0.2
  font_awesome_flutter: ^10.8.0
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  flutterwave_standard: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0
  build_runner: ^2.5.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_pagination: ^4.1.0
  firebase_database: ^11.3.7
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/