name: project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  gap: ^3.0.1
  logger: ^2.5.0
  json_annotation: ^4.9.0
  intl: ^0.17.0
  timeago: ^3.3.0
  cached_network_image: ^3.4.1
  iconsax_flutter: ^1.0.0
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/